env:
  global:
    BUILD_ON="amd64"

os: linux
dist: focal

stages:
  - build

services:
  - docker

_debian_package_build_template: &debian_package_build_template
  stage: build

  before_install:
   - docker pull ${DOCKER_IMAGE}

  script:
   # Store build results in /tmp/buildd-results
   - mkdir -p /tmp/buildd-results
   - |
     docker run \
       -e CI \
       -e TRAVIS \
       -e HAS_JOSH_K_SEAL_OF_APPROVAL \
       -e RELENG_FULL_BUILD \
       -e TRAVIS_COMMIT \
       -e TRAVIS_TAG \
       -e TRAVIS_BRANCH \
       -e TRAVIS_EVENT_TYPE \
       -v /tmp/buildd-results:/buildd \
       -v ${PWD}:/buildd/sources \
       ${DOCKER_IMAGE} \
       /bin/sh -c "cd /buildd/sources ; apt install -y python3-git ; ./build_package.sh"

  deploy:
    provider: releases
    edge: true # use dpl v2
    draft: false
    file:
      - /tmp/buildd-results/*.deb
      - /tmp/buildd-results/*.dsc
      - /tmp/buildd-results/*.changes
      - /tmp/buildd-results/*.tar.*
    on:
      tags: true
      condition: -n $RELEASES_TOKEN

_bullseye_amd64_full_env_filter: &bullseye_amd64_full_env_filter
  if: env(BUILD_ON) =~ /^amd64 ?/ AND (branch =~ /^(feature\/)?bullseye(\/)?.*$/ OR (tag =~ /^hybris-mobian\/bullseye\/.*$/))

_bullseye_amd64_dep_env_filter: &bullseye_amd64_dep_env_filter
  if: env(BUILD_ON) =~ / amd64/ AND (branch =~ /^(feature\/)?bullseye(\/)?.*$/ OR (tag =~ /^hybris-mobian\/bullseye\/.*$/))

_bullseye_arm64_full_env_filter: &bullseye_arm64_full_env_filter
  if: env(BUILD_ON) =~ /^arm64 ?/ AND (branch =~ /^(feature\/)?bullseye(\/)?.*$/ OR (tag =~ /^hybris-mobian\/bullseye\/.*$/))

_bullseye_arm64_dep_env_filter: &bullseye_arm64_dep_env_filter
  if: env(BUILD_ON) =~ / arm64/ AND (branch =~ /^(feature\/)?bullseye(\/)?.*$/ OR (tag =~ /^hybris-mobian\/bullseye\/.*$/))
  
########################################################################

jobs:
  include:

  # Debian bullseye AMD64 (x86_64)
  # - route for full builds (arch-dep, arch-indep and source)
  - name: bullseye-amd64-full
    arch: amd64
    env:
      - DOCKER_IMAGE="hybrismobian/build-essential:bullseye"
      - RELENG_FULL_BUILD="yes"
    <<: *bullseye_amd64_full_env_filter
    <<: *debian_package_build_template

  # Debian bullseye AMD64 (x86_64)
  # - route for only arch-dep builds
  - name: bullseye-amd64-dep
    arch: amd64
    env:
      - DOCKER_IMAGE="hybrismobian/build-essential:bullseye"
      - RELENG_FULL_BUILD="no"
    <<: *bullseye_amd64_dep_env_filter
    <<: *debian_package_build_template

  # Debian bullseye ARM64 (AArch64)
  # - route for full builds (arch-dep, arch-indep and source)
  - name: bullseye-arm64-full
    arch: arm64-graviton2
    virt: vm # required to route the job to arm64-graviton2
    group: edge # required to route the job to arm64-graviton2
    env:
      - DOCKER_IMAGE="hybrismobian/build-essential:bullseye"
      - RELENG_FULL_BUILD="yes"
    <<: *bullseye_arm64_full_env_filter
    <<: *debian_package_build_template

  # Debian bullseye ARM64 (AArch64)
  # - route for only arch-dep builds
  - name: bullseye-arm64-dep
    arch: arm64-graviton2
    virt: vm # required to route the job to arm64-graviton2
    group: edge # required to route the job to arm64-graviton2
    env:
      - DOCKER_IMAGE="hybrismobian/build-essential:bullseye"
      - RELENG_FULL_BUILD="yes"
    <<: *bullseye_arm64_dep_env_filter
    <<: *debian_package_build_template
